import Navbar from '@/components/Navbar'
import './globals.css'
import { Space_Mono } from 'next/font/google'

const space_mono = Space_Mono({
  weight:['400', '700'],
  subsets: ['latin'],
  
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={space_mono.className}>
        <div className="grid min-h-screen place-content-center bg-slate-900 text-white p-4 ">
          <div className="sm:w-[500px] md:w-[600px] lg:w-[700px]">
            <Navbar/>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
